version: '3.4'
services:
  db:
    container_name: db
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
  php:
    image: php:7-fpm
    volumes:
      - ./:/app
    depends_on:
      - db
    restart: always
  nginx:
    image: nginx:latest
    depends_on:
      - php
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    links:
      - php
    restart: always